### ISSUE TITLE
How should we handle non-numerical item prices outside of restricted?

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#115]
Some items have prices like `Special/ (R) 100`. How should we handle instances like this?

https://docs.google.com/spreadsheets/d/1FgGOmFdgbqTx8l4HVCT0huPdtztDUfzaZB04ur-SB6M/edit#gid=2094253977&range=6:6

**Comment by AndreLemay** [comment]
I would think we shouldn't put that in the price column at all. What does "Special" even mean in this case? I have to imagine the book includes some extra description that explains it. I would think having a "Notes" column or something like that would be best for weird edge cases like this.

**Comment by duffn** [comment]
I agree. A "Notes" column is in order.

**Comment by bknowles** [comment]
How about “Not For Sale”, like I’ve seen used on a number of unique items in G&G?

**Comment by duffn** [comment]
That sounds perfectly reasonable.

Should we have another special condition for the price column like restricted or should this go into the notes? A special condition sounds okay if "not for sale" happens often, but I'd like to avoid too many of these.

**Comment by AndreLemay** [comment]
I think it happens fairly often in things like g&g or the era books, as they include unique weapons and things like landos cape, Han's blaster, etc.

Should be easy enough to add another condition.

**Comment by duffn** [comment]
Excellent. https://github.com/duffn/theouterrim/issues/122
