### ISSUE TITLE
Cendiary Priest is missing its index.

### ISSUE THREAD

**Issue by AndreLemay** [duffn/theouterrim#118]
![image](https://user-images.githubusercontent.com/787013/75613362-93adbe00-5ae1-11ea-9f73-b20fafcd29f4.png)

In Adversaries.

According to [stoogoff](http://swa.stoogoff.com/#cendiary-priest), it's from Nexus of Power, but don't know what page.

**Comment by AndreLemay** [comment]
Same for Built-in Comlink in Adversaries-Gear:
![image](https://user-images.githubusercontent.com/787013/75613394-0cad1580-5ae2-11ea-9906-fc5d91e22574.png)

**Comment by duffn** [comment]
The priest is on page 36.
