### ISSUE TITLE
Add field for resource flavor text

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#120]
It would be good to have a spot for flavor text for a resource if necessary.

LAAT flavor text example: https://star-wars-rpg-ffg.fandom.com/wiki/4R3_Light_Assault_Transport

**Comment by bknowles** [comment]
IANAL, and this cannot be construed to be legal advice.

That said, the risk with all fluff and flavor text is that has been shown by legal precedent to be fully copyrightable, whereas tabular information is more difficult to copyright.

So, a C&D letter sent to your hosting provider could get the entire site taken down permanently, and your code taken off GitHub. And it could be tough to get them put back online, even in a reduced state.

You want to think long and hard about how close you want to get to the copyright razor edge. And make sure you get actual legal advice from someone who is a lawyer and a member of the bar in the appropriate jurisdiction for you.

**Comment by duffn** [comment]
Even if you're not a lawyer, that's enough for me. I have no interest in remotely coming close to dealing with anything like that.
