### ISSUE TITLE
Add page loading indicator

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#131]
The book pages are slow to load, particularly on mobile. Add some sort of indicator to let the user know that the page is loading.

https://www.gatsbyjs.org/packages/gatsby-plugin-nprogress/

**Comment by duffn** [comment]
Maybe this isn't possible without additional work, because the page isn't actually waiting to load, it's the tables that are waiting to render, so everything is blocked on the page, even a progress loading indicator like nprogress or pace.

**Comment by AndreLemay** [comment]
We'd have to make the table rendering asynchronous. So probably we'd need some sort of state on the page components that isn't set until all the async stuff is done, and also controls whether a loading message or the table is rendered.

Would also be good to see if the delay is in the graphql query or the rendering itself, as the former would require looking into async querying on the Gatsby side.

**Comment by duffn** [comment]
There are no runtime queries since the site is just static, so it’s just the amount of tables on the page.
