### ISSUE TITLE
Research using the FFG dice font

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#14]
https://www.reddit.com/r/swrpg/comments/f6nyyh/introducing_the_outer_rim_swrpg_stats_site_and/fi8xd4d?utm_source=share&utm_medium=web2x

- ~~Where do I find this font?~~ http://thealexandrian.net/wordpress/37660/roleplaying-games/star-wars-force-and-destiny-system-cheat-sheet
- Are there any legal implications of using it?
- Does it look good on the site?

**Comment by bknowles** [comment]
There’s one character that is missing in that font — the split white/dark force pip. I think we may have used a different font that included that character in the fan-made book “Spark of Rebellion”. I’ll have to see if I can dig up that other version of the font.

**Comment by duffn** [comment]
Added here https://github.com/duffn/theouterrim/pull/383
