### ISSUE TITLE
Prices are sorted as strings in the table filter

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#142]
Minor importance.

![ADCE8E75-1C57-4351-BFAF-D01CF108BE13](https://user-images.githubusercontent.com/3457341/75649370-2187c700-5c10-11ea-8dc4-b39144d29153.jpeg)

**Comment by AndreLemay** [comment]
Not sure how much sense it even makes to filter by price tbh. The only filter that would make sense is if you could put in < or > some value. Just listing all the individual values and filtering by one doesn't seem like something anyone would ever need to do.

**Comment by duffn** [comment]
Yeah, I suppose you're right. Is >< a doable option with the table? If not, this could even be turned off.

**Comment by AndreLemay** [comment]
It does look like mui-datatables supports custom filtering logic and rendering, so I think we can probably get it to do whatever we want. See these examples:

Custom filter options: https://github.com/gregnb/mui-datatables/blob/master/examples/column-filters/index.js

Custom logic/option display: https://github.com/gregnb/mui-datatables/blob/master/examples/customize-filter/index.js

**Comment by duffn** [comment]
That's great, thanks for finding that! At some point this would be nice, but not high priority. Really want to get as much data in as we can and get brawn damage working.

**Comment by AndreLemay** [comment]
I can get started on that. It seems we don't have any data from gadgets and gear yet, and I've got a copy, so I can probably start adding data from that, and using it to determine what does and doesn't get the + since it should have a good chunk of the weapons from all the other books.

**Comment by duffn** [comment]
We don't have any data on the site as of yet, but @bknowles has got a great jump on recording from G&G: https://docs.google.com/spreadsheets/d/1KKQN3VVQ6aFMIPVOkObT_vRt8Vyb8Hhg-46HOlfV-xY/edit#gid=251391118

**Comment by AndreLemay** [comment]
oh, awesome. In that case I'll leave the data-entry to him, but I'll use it for determining what gets the +

**Comment by duffn** [comment]
And for any data that I've already entered from other spreadsheets, there is a `brawn` field that is `true || false`.

**Comment by AndreLemay** [comment]
Excellent, I'll follow that.

**Comment by bknowles** [comment]
> Not sure how much sense it even makes to filter by price tbh. The only filter that would make sense is if you could put in < or > some value. Just listing all the individual values and filtering by one doesn't seem like something anyone would ever need to do.

Well, actually, with any numbers of any sort, I really want to be able to do all sorts of equality filtering. So, not just the items of Rarity 6, but all items of Rarity 6 and below. Or all items doing 12 or more points of damage. Or all items having Blast 5 or above. Etc.....

**Comment by bknowles** [comment]
I’m hoping to get more work on G&G done tonight.

**Comment by AndreLemay** [comment]
It looks like we should be able to do all that, though I think we'll have to make a separate issue(s) for all those cases

**Comment by duffn** [comment]
> Well, actually, with any numbers of any sort, I really want to be able to do all sorts of equality filtering. So, not just the items of Rarity 6, but all items of Rarity 6 and below. Or all items doing 12 or more points of damage. Or all items having Blast 5 or above. Etc.....

👍 https://github.com/duffn/theouterrim/issues/153

**Comment by AndreLemay** [comment]
@duffn I think we can close this now, no?

**Comment by duffn** [comment]
Yep, the filter should cover this, thanks!
