### ISSUE TITLE
Exported data from table has book IDs and not names

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#145]
- Export any table
- Get a download like

```
"generatedId","restricted","Name","Category","Price","Rarity","Encum.","Index"
"d073c437-d243-4d7f-9f2e-42f87c76f587","","Advanced Flesh Camouflage Kit","Security","2500","7","2","f34ec89d-b99e-4b0c-b9c6-562894526075:193"
"8d157b00-5152-47b0-bc5b-24aa9bf58575","","Assassin Droid","Droids","65000","8","0","f34ec89d-b99e-4b0c-b9c6-562894526075:427, 37ee73a9-01c8-440c-a734-ea52e2ff780a:410"
```

**Comment by bknowles** [comment]
> * Export any table
> * Get a download like
> 
> ```
> "generatedId","restricted","Name","Category","Price","Rarity","Encum.","Index"
> "d073c437-d243-4d7f-9f2e-42f87c76f587","","Advanced Flesh Camouflage Kit","Security","2500","7","2","f34ec89d-b99e-4b0c-b9c6-562894526075:193"
> "8d157b00-5152-47b0-bc5b-24aa9bf58575","","Assassin Droid","Droids","65000","8","0","f34ec89d-b99e-4b0c-b9c6-562894526075:427, 37ee73a9-01c8-440c-a734-ea52e2ff780a:410"
> ```

😱

**Comment by AndreLemay** [comment]
This is a result of the index link changes. I'll see if I can take a look tonight, if not I should be able to get to it tomorrow

**Comment by duffn** [comment]
Thanks @AndreLemay!
