### ISSUE TITLE
Numerical column filtering should allow for ranges

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#153]
When filtering (or maybe some sort of advanced searching) on numerical columns, we could allow, should allow for range options. 

https://github.com/duffn/theouterrim/issues/142#issuecomment-593714973

Split this issue into multiple for different numerical columns after an approach is decided upon.

**Comment by AndreLemay** [comment]
With any luck we'll be able to handle pretty much all the columns with the same base implementation, then possibly add some specific implementations as needed

**Comment by duffn** [comment]
Thanks for the pricing filtering in #233 @AndreLemay! Is this easy to apply to other numerical fields?
