### ISSUE TITLE
Investigate refactoring BookDataProvider 

### ISSUE THREAD

**Issue by AndreLemay** [duffn/theouterrim#160]
Right now it's super basic and just encapsulates a graphql query, returning the raw data, leaving consumers to do anything useful with it.

Given that it's being used in nearly-identical ways in multiple places already, it would be a good idea to refactor it, possibly into some sort of singleton that provides an api to get book data.

Questions: 

- How much should this expose? If we just expose the full set of book data, are we just re-inventing the graphql wheel?

**Comment by duffn** [comment]
https://github.com/duffn/theouterrim/pull/380
