### ISSUE TITLE
Pagination in a table creates incorrect index links

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#166]
Something is wrong with the index column and pagination.

### Example

- Go to https://theouterrim.co/adversaries/
- Search for `Physician`, for example.
- Note that `Physician` has these incorrect indices

```
Force and Destiny Beginner Game - Rulebook:47, Age of Rebellion Core Rulebook:430, Citizens of the Galaxy Adversary Deck:4
```

- Go to the `Physician` individual entry https://theouterrim.co/adversaries/5e828dde-0a6a-47ca-8b75-8a94a160d291/

- Note the correct indices of

```
Age of Rebellion Core Rulebook:430, Citizens of the Galaxy Adversary Deck:4
```

- Go to the AoR Core Rulebook and find that `Physician` has even different indices.

This is happening with other items, too.

It appears to have started with the change to links in the index column:
https://www.gatsbyjs.com/dashboard/15a2fa68-6352-4809-a35f-c4336103c44d/sites/1ec452ab-6722-4232-9876-84a1fd71badc/builds/5ada4209-e2a6-475a-9a47-ef12e9ebaa8c/details?returnTo=%2Fdashboard%2F15a2fa68-6352-4809-a35f-c4336103c44d%2Fsites%2F1ec452ab-6722-4232-9876-84a1fd71badc%2Fproduction

@AndreLemay if you could take a look at this, that would be great! We could attempt to revert the links if this is going to take awhile to debug

**Comment by AndreLemay** [comment]
That is indeed strange, I'll take a look.
