### ISSUE TITLE
Update graphQL queries to just use nodes instead of edges and nodes

### ISSUE THREAD

**Issue by AndreLemay** [duffn/theouterrim#186]
As per docs here: https://www.gatsbyjs.org/docs/graphql-reference/#a-longer-query

Instead of a graphQL query like this:
`{
  allSitePlugin {
    totalCount
    edges {
      node {
        name
        version
        packageJson {
          description
        }
      }
    }
  }
}`

it can instead be simplified to just use nodes:
`{
  allSitePlugin {
    totalCount
    nodes {
        name
        version
        packageJson {
          description
        }
    }
  }
}`

This allows us to eliminate all the repetitive and pointless
`data.whateverYaml.edges.map(({node}) => node)`
with 
`data.whateverYaml.nodes`

**Comment by duffn** [comment]
Fixed in #265.
