### ISSUE TITLE
Change weapons attachment section name

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#203]
As these included all attachments, somebody suggested `Weapon, Armor, and Gear Attachments`.

I suppose if we really wanted to change the URL, we could do that too and add a redirect into Netlify.

**Comment by AndreLemay** [comment]
Alternatively, if we don't want to deal with grouping, we could always split the data by category and have 1 table for each category, using "<category> attachments" as the title (would require a bit of data cleaning, as we've currently got a "ranged weapon attachments" category)

**Comment by duffn** [comment]
That's a possibility. Right now, I'm just thinking change the title on the table and that's it. :man_shrugging:

**Comment by duffn** [comment]
Okay, maybe I'll just make the entire change here in #221.
