### ISSUE TITLE
Humanize all numbers in tables and individual cards

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#209]
Ex. Encumbrance, crew, and everything else. 

![BD85C143-1174-4C4A-8475-B58E6B943EAF](https://user-images.githubusercontent.com/3457341/76134802-6def5000-5fde-11ea-992e-c7378ee0c638.jpeg)

**Comment by bknowles** [comment]
I’m confused. What do you mean by “humanizing” the numbers?

**Comment by duffn** [comment]
Commas or periods where necessary. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
