### ISSUE TITLE
Add ability to show all items in a table

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#22]
As requested here, it would be nice to allow users to show all of the items in a table instead of just the preconfigured number of records. https://www.reddit.com/r/swrpg/comments/f6nyyh/introducing_the_outer_rim_swrpg_stats_site_and/fi6vw7h?utm_source=share&utm_medium=web2x

It's not immediately clear how to do this from the material table docs, so we could just hack a 1000 or something large in the `pageSizeOptions` for a short-term band-aid: https://github.com/duffn/theouterrim/blob/885fa6f8b1a7e6feaa910a1737160d4c897adcf7/src/components/shared/Table.js#L33

**Comment by AndreLemay** [comment]
Found a way to do this that seems intended based off the mui docs [here](https://material-ui.com/components/tables/#custom-pagination-options)

But it results in this slightly ugly thing:
![image](https://user-images.githubusercontent.com/787013/75083032-93f7f900-54e4-11ea-84f0-a6bdf173b8fc.png)

Haven't yet found a way to get that to display something a bit nicer

**Comment by duffn** [comment]
Thanks! I posed that question here, but didn't actually even try it. https://github.com/mbrn/material-table/issues/1685

Interesting that it works, but displays like that. That is indeed ugly.

**Comment by duffn** [comment]
Handled in #52.
