### ISSUE TITLE
Portable Plasma Shield from CotR - wrong attachment type

### ISSUE THREAD

**Issue by bknowles** [duffn/theouterrim#237]
The page at https://theouterrim.co/weapon-attachments/21d8c2c6-022f-40ec-883f-915afcae8556/ says that this is a weapon attachment, but my copy of the book itself says that this is an armor attachment.

**Comment by duffn** [comment]
Yes, this is confusing. The whole section is called `Weapon Attachments` when it's actually attachments for more than just weapons.

I'm currently working on this in #203.

**Comment by duffn** [comment]
The section has been renamed to `Attachments`, so this should be clearer now.
