### ISSUE TITLE
Create a logo for the site

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#29]
I made the favicon with some online generator, but it would be very cool to have a logo for the site. I’m not sure exactly what I’d be looking for but am open to suggestions. For reference I do like the SWSheets logo. It’s clean, simple and Star Wars-esque.

I’ll certainly need help in this department!

**Comment by AndreLemay** [comment]
My wife actually happens to be a graphic designer, I'll see if she can whip something up.

**Comment by duffn** [comment]
Wow, that would be incredible!
