### ISSUE TITLE
Upgrade material-ui to V5

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#370]
Follow the huge amount of steps here: https://mui.com/material-ui/migration/migration-v4/

**Comment by Pavan-Nambi** [comment]
hey can i work on this?

**Comment by duffn** [comment]
Yes, that would be great, thanks!

**Comment by Pavan-Nambi** [comment]
hey
 acc to docs its better to verify everything is working correctly or not after every step of upgrading but even when i discard all changes app is not starting its returning error...
![image](https://user-images.githubusercontent.com/92514129/210298905-cc160bf1-e942-4acb-ac5a-88a1743407b9.png)
should i just make changes without checking? or should i wait until it get resolved or am i doing anything wrong here..?

**Comment by Pavan-Nambi** [comment]
acc to bit google search its saying its due to node js version incompatibility should i degrade to pre v17....???

**Comment by duffn** [comment]
Thanks for giving this a go. I'd actually hold off for now. I'm reconsidering use of Gatsby entirely in fact. It's far too complex for this project and I'm not enjoying working with it any longer.

**Comment by duffn** [comment]
https://github.com/duffn/theouterrim/pull/380
