### ISSUE TITLE
Damage for melee weapons missing the "+" sign

### ISSUE THREAD

**Issue by sajro94** [duffn/theouterrim#45]
I took a look at the data, and it seems that all weapons that should have a + sign at the front of their damage are missing it, making it difficult to determine which weapons benefits from brawn and which doesn't.

**Comment by duffn** [comment]
Thank you for the issue! I was just chatting with another user about this as we add new content. This definitely needs to be fixed.

**Comment by bknowles** [comment]
> I took a look at the data, and it seems that all weapons that should have a + sign at the front of their damage are missing it, making it difficult to determine which weapons benefits from brawn and which doesn't.

That was always a problem on the Viluppo site. We started off with all melee weapons have a +, and only lightsabers don’t so lightsabers got put into a different category. And then along the way other melee weapons that also didn’t. And things just got messier from there.

I’m not sure what the right solution is, but I would urge caution before just launching into something that could make life more difficult in the future.

**Comment by duffn** [comment]
I'm okay with adding `+` if that's they way the books represent this. I'd like to get as close as possible to the rules as written as we can.

The slightly annoying thing (to me) about this is that this breaks sorting in the tables, since `damage` will have to be a string.

**Comment by sajro94** [comment]
Would it be possible to add a property to weapon objects in the dataset, that states if they add brawn or not?
That way the actual damage property doesn't need to be a string and the "+" sign can be added only at the rendering time?

**Comment by duffn** [comment]
That's a good idea. Let me play around with a few different options.

**Comment by bknowles** [comment]
I think that’s what Jake ended up doing in the Viluppo index.

**Comment by AndreLemay** [comment]
Just to update this, I've got essentially the same behaviour working with the price column adding the (R) on restricted ones. Should be easy to extend that to handle this case as well, though it would be great to actually identify all the weapons that should have this + beforehand and put them in a list. Would be much easier to just add the new field as false on all items, then go through the list and update the data accordingly.

Once the mui-datatable conversion PR is merged, I can open a PR to merge in the fix for #61, and then fix this on top of that.

**Comment by duffn** [comment]
Awesome, merged!

**Comment by duffn** [comment]
> Should be easy to extend that to handle this case as well, though it would be great to actually identify all the weapons that should have this + beforehand and put them in a list. Would be much easier to just add the new field as false on all items, then go through the list and update the data accordingly.

I don't know how to identify this en masse beforehand and am open to suggestions.

**Comment by duffn** [comment]
So for the old weapons, they’ll get caught when old books are audited which is happening right now.

**Comment by duffn** [comment]
I think this one is the most important of all of the "special conditions" because without it, we're entirely excluding an important part of damage with the "+". The others all just pertain to sorting and this one is leaving something out entirely.

**Comment by duffn** [comment]
The ability to show "+" brawn damage was added to the tables in #187 and will be added to the individual item detail in #197.

This still requires the data to be updated, but the code is in place to show "+" when necessary.

**Comment by duffn** [comment]
The above is now complete. Again, the historical data needs to be updated, but the functionality is there to show "+" brawn damage.
