### ISSUE TITLE
Investigate alternatives to material-table

### ISSUE THREAD

**Issue by AndreLemay** [duffn/theouterrim#48]
Material-table is not quite meeting all our needs, with certain other issues (#24 #22 ) being made very difficult due to use of material-table.

We should look into some alternatives and see if any can do what we need, or if we'll need to implement our own based on mui components.

Possible alternatives:
- https://github.com/gregnb/mui-datatables

**Comment by duffn** [comment]
I like this idea a lot, if we could make it work with whatever solution. https://github.com/duffn/theouterrim/issues/49

Material table does have a `searchText` prop which I got to work with URL params, so at least that was one convenient thing about it.

**Comment by AndreLemay** [comment]
So it's looking like mui-datatables might actually be a good fit for what we want. I've got it up and running locally (will probably push soon to my fork so you can check it out), and it's got the sticky headers by default, seems to support all the options that material-table did. It actually has the exact same searchText prop, along with page and rowsPerPage props to set those initial values. 

Was able to get the headers to stick to under the navbar, but I'm thinking we'll need to make it an option on our Table component, because it won't work on multi-table pages.

I've also been able to get the "All" pagination option to work correctly, though I imagine my solution would apply to material-table as well, as it's just a matter of getting the length of the data passed in the props and using that as the value instead of -1 (no idea why mui use that as their example).

It also supports various responsive layouts on smaller screens, with the default being switching to a "stacked" card view (basically a 2 column table with field name and value as the columns, and each row is in a card).

Only thing we'd be losing is the grouping, but it's possible we could add that in ourselves (would probably have to take a look at material-table's implementation to get an idea how they do that and if we could integrate it).

**Comment by duffn** [comment]
Wow, this is amazing! I can't wait to see it.

**Comment by AndreLemay** [comment]
See here: https://github.com/AndreLemay/theouterrim/tree/mui-datatables

Still some minor styling issues (wide tables have no right padding for some reason), but otherwise more or less functional.

One thing to note though is that while the "All" option works, it also tanks performance

**Comment by duffn** [comment]
Awesome. Do you want to open a draft PR and then we can jam on it from there?

**Comment by duffn** [comment]
> One thing to note though is that while the "All" option works, it also tanks performance

One quick note here is that this doesn't feel too bad to me. If you're running in dev mode, yes, it's terrible.

But if you `yarn build && yarn serve` which is what will run in prod, then it's not too bad.

**Comment by AndreLemay** [comment]
Ran into a bit of forced stupidity thanks to mui-datatables.. Basically the custom render function for a column receives this table metadata object they generate (instead of just the literal data object for that row).

Unfortunately it seems the creators of mui-datatables thought it would be a great idea to just totally mangle the data you give the table before passing it into these render functions, with these results:

1) "generatedId" needs to actually be set as a column (though we can set it to not display in the table), otherwise it doesn't exist in the rowData object that gets passed in.

2) For whatever reason, this rowData object has totally meaningless keys. They're just numbered by the index of the column in the initial array you pass in. 

What this means for us is that if we want to use mui-datatables, and we want to have custom cell rendering for certain columns (which I think is a yes to both), we're going to have to just have an accepted convention on how to handle the generatedId columns in the project. My suggestion would be to have it always be the first column, then when we need to get it from the rowData we know it's always going to be rowData[0].

End result look like this:

![image](https://user-images.githubusercontent.com/787013/75121734-d1839000-5664-11ea-9cb7-027e31c03834.png)

I'm not generally a fan of magic numbers, but there doesn't seem to be any other way to handle this.

**Comment by duffn** [comment]
Well, that's unfortunate. We _definitely_ need to custom render columns so we can put in links. And, I _think_ we'll want to move to mui-datatables.

I don't feel like this is a blocker yet. The above is certainly annoying, but I think we could make due.

**Comment by AndreLemay** [comment]
Yeah we can definitely work around it. Maybe put some logic into the table itself to inject the generated id column. Or have some sort of column factory that handles it, and have each component call into that to generate its column array.

**Comment by AndreLemay** [comment]
One more potential issue, not sure how you'd want to solve it.

The gist is that the tables aren't horizontally restricted to their container (most noticeable on the starships page). There are a couple solutions that bring their own problems.

Solution 1: Make the table scroll horizontally
This is probably the best looking solution, as it keeps everything fitting nicely on the page, however it completely breaks the sticky header behavior, and I'm not sure there's any way around that. The problem there is down to how position: sticky works. As stated [in the docs here](https://developer.mozilla.org/en-US/docs/Web/CSS/position):

> Note that a sticky element "sticks" to its nearest ancestor that has a "scrolling mechanism" (created when overflow is hidden, scroll, auto, or overlay), even if that ancestor isn't the nearest actually scrolling ancestor. 

What this means for us is that because of how the page is structured, if we make the table horizontally scrollabe, it becomes the nearest ancestor with a scrolling mechanism, so the headers position is fixed relative to the table itself, so we'd pretty much have to set the tables to a fixed height (as big as fits in the viewport I guess for single table pages) and have all scrolling occur exclusively within the table. If we go this route, I think we should reduce how much vertical white-space we have on the page, and maybe see if we can have the rows wrap text less so we can actually fit more rows on screen at one time.

Solution 2: Make the entire page scroll horizontally
This has the advantage of working just fine with the sticky headers, but it breaks all the nice padding we have around the tables, because basically the table container remains the width of the viewport, while the table itself just overflows that completely and goes off to the right edge of the page. I tried putting padding/margins on that side, but for some reason the paper's box shadow wouldn't apply so it looks bad.

As an aside, while mui-datatables don't natively support any kind of grouping behaviour, we could implement grouping similar to how I did it on my site. Basically I just provide the table with a groupByField, and a dictionary to map values for the grouping field to the label for that group, and then I just sort the data into buckets by group, and with each group, insert a spanning row with the group label, then all data rows for that group. We'd also probably want to provide a custom sorting function that would sort within each group so that we don't break the grouping. I imagine we could have some sort of ui hook for users to choose a column to group by, then we'd remove that column from the table and add in all the group label rows (could probably even have them stick under the headers like my site does). I think this should be possible using mui-datatables, so if you're interested, I can open another issue to investigate that once the PR for this issue is all cleaned up and merged.

**Comment by duffn** [comment]
Displaying things in a table exactly like we want it is damn hard!

I really like the sticky header. It feels really useful to me. And the more that I play around with the current setup, I don't feel like the horizontal scrolling on mobile is _that_ terrible, so if we have scrolling horizontally, that seems okay to me. 

What do you think?

I'll note that right now, 55.7% of the traffic is mobile, though the sample size is small and much of that could be due to people coming from mobile Reddit from the launch post.

**Comment by AndreLemay** [comment]
I agree that the horizontal scrolling is probably fine on mobile, I was able to get it looking nice with the  right side of the paper as well, though it required tweaking the layout so the container component no longer has a max width, but I think that's a fine compromise.

Still need to fix the layout on the individual book page (and anywhere else that has multiple table I guess), but once that's done I think the PR might be ready for merging.

**Comment by duffn** [comment]
Excellent! I’ll try to take another pass at the PR today.

**Comment by duffn** [comment]
Handled in #52.
