### ISSUE TITLE
Specials columns have trailing commas

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#65]
Remove all the trailing commas from the Specials columns. 

![01A97723-41A5-4364-9BC8-9F9A74AF8FB7](https://user-images.githubusercontent.com/3457341/75129644-11f40580-5687-11ea-9589-512c2eb39d7e.jpeg)

**Comment by AyoAlfonso** [comment]
To be replaced with?

**Comment by duffn** [comment]
To be removed entirely. I’m just talking about the trailing commas, i.e. the comma after `Stun Damage` above.

**Comment by AndreLemay** [comment]
Might be related to prettier settings. I've noticed it sometimes likes to add trailing commas to array and object declarations (though it's been inconsistent).

Possible it did the same on the yaml files.

**Comment by duffn** [comment]
This is just straight from Viluppo, so I don't think it has anything to do with prettier.

**Comment by AndreLemay** [comment]
Ah, ok. Might be worth double checking that prettier won't just undo this at someone point in the future, but I haven't really looked at the data files yet, so I have no idea of prettier even touches them.
