### ISSUE TITLE
Duplicate entries for beam splitter

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#75]
https://theouterrim.co/weapon-attachments/ab3cf688-c1f5-4b60-a9d3-13bfa8adf604/
https://theouterrim.co/weapon-attachments/27b5f2db-01d4-4475-b20a-1777af4d4b00/

**Comment by bknowles** [comment]
I've found a few duplicates.  In the Viluppo index, I know we had some items that were almost duplicates, except for one or two minor things.  Slightly different versions of the same gear, from different books.  I'm not sure if you'll see the same kind of thing here, or not.  But I will try to remember to flag duplicates as I see them.

**Comment by duffn** [comment]
Fixed in #78.
