### ISSUE TITLE
Add dice representations in tables 

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#82]
Add dice representations in tables, replacing the specific dice place holder text.

Ex. https://theouterrim.co/qualities/3773543e-aab3-410a-a1bc-f3dcc1f1423d/ Replace `[BOOST]` with something that looks like a boost die. 

- Find or make these resources. 
- Replace the text with the resource.
- Ensure this doesn’t adversely affect performance too much.

**Comment by AndreLemay** [comment]
Related: #14 

@bknowles Have you been able to dig up the font you mentioned?

I think it should be possible to create some static components that essentially return a span with its font set to this image font, and then grab the right character from the font. I know my employer does something like this for icons, though I'm not 100% sure on the details of the implementation.

**Comment by bknowles** [comment]
I still need to find my font files. They’re somewhere on my personal laptop, but I’m not sure where.

I think we should definitely be able to use a web font for making these things look their best, and we may be able to find or make our own web font based on the files I have.

**Comment by duffn** [comment]
Added dice icons here https://github.com/duffn/theouterrim/pull/383
