### ISSUE TITLE
Link adversaries to stoogoff

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#85]
http://swa.stoogoff.com, https://github.com/stoogoff/sw-adversaries is great. I like it a lot.

I want to link our adversaries directly to the adversary on stoogoff. There's a lot of useful functionality there that is not here and with no plans to replicate it.

I'm not sure what this is exactly going to look like yet, but am open to suggestions.

- Link in the table?
- In an adversary detail?
- Both?

**Comment by bknowles** [comment]
What about building the adversaries in SWSheets.com, and then linking to them there?

I mean, I think he’s probably got a good starting point, but I think we can probably do better. Albeit, with more work.

**Comment by AndreLemay** [comment]
That could work, but I think linking to stoogoff could be a good starting point, then eventually once we start getting all these issues closed off and the site stabilized, we can come back to that.

**Comment by duffn** [comment]
I really don't have any interest in rebuilding any of the already good functionality there, so let's just link to it.
