### ISSUE TITLE
How should we handle non-numerical defense on vehicles?

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#97]
For example, in RotS the LAAT/i was listed with this defense. How do we handle things like this?

`1 / - / - / 1`

https://docs.google.com/spreadsheets/d/1FgGOmFdgbqTx8l4HVCT0huPdtztDUfzaZB04ur-SB6M/edit#gid=1356868558&range=4:4

**Comment by bknowles** [comment]
That’s because it’s so small that it doesn’t have those separate areas as far as the armor is concerned.

**Comment by AndreLemay** [comment]
Aren't all ship defense values displayed this way? I would think keeping the format and storing as a string would be best. If not, we should separate into 4 defense int fields in the data, then have a single column that combines them. 

Not sure if any ships have 0 instead of - as a defense value, but we could always use -1 to represent -

**Comment by duffn** [comment]
Oh hell, you're right. For some reason, I was thinking we were breaking current functionality by adding defenses like this, but we don't have ship defense in there at all right now.

I think this will be fine as a string.

**Comment by AndreLemay** [comment]
We should probably disable sorting on the column as well, since there isn't really a sensible way to do so.

**Comment by duffn** [comment]
Agreed.

**Comment by bknowles** [comment]
> Not sure if any ships have 0 instead of - as a defense value, but we could always use -1 to represent -

Yes, there are some ships I recall seeing that actually have zero armor or defense in certain zones, as opposed to not having those zones at all.

Welcome to the wonderful world of FFG consistency! 🤣

**Comment by duffn** [comment]
Thanks FFG. 🤦‍♂ 

Well, in this instance at least it’s fine, because this column will just be a string and we won’t sort it.
