### ISSUE TITLE
How should we handle "-" encumbrance and crit on items?

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#98]
The Fusion Shunt attachment from WotS has a `-` as the encumbrance, and from what I've been told that's distinctly different than `0`. 

How should we handle this and other items with "-" encumbrance or crit?

https://docs.google.com/spreadsheets/d/1FgGOmFdgbqTx8l4HVCT0huPdtztDUfzaZB04ur-SB6M/edit#gid=1200894504&range=9:9

**Comment by bknowles** [comment]
As an attachment, I think it should have no Encumbrance. It would have an HP requirement, but not an encumbrance.

If it was a separate item, it might have an encumbrance, perhaps of zero. But this is an attachment.

**Comment by duffn** [comment]
I'm seeing this a lot in the spreadsheets. This may warrant another special condition sort like restricted pricing.

**Comment by AndreLemay** [comment]
Probably. I'm not sure how consistent the books are on when to use 0 vs "-" or even what the difference is mechanically.

I do remember seeing something like "10 items of 0 encumbrance can be counted as 1 encumbrance" somewhere in the rules. Could be things with no encumbrance don't count towards that even.

**Comment by duffn** [comment]
I suppose we should handle the "-" case for both encumbrance and crit then.

https://github.com/duffn/theouterrim/issues/124
https://github.com/duffn/theouterrim/issues/122
